---
version: "3.8"
services:
  jore4-auth:
    container_name: auth
    build:
      context: ".."
    restart: "unless-stopped"
    depends_on:
      jore4-testdb:
        condition: service_healthy
    ports:
      - "127.0.0.1:3200:8080"
    environment:
      API_PATH_PREFIX: ""
      API_PATH_PREFIX_PUBLIC: "/api/auth"
      DB_SESSION_SCHEMA: "public"
      LOGINPAGE_URL: "http://localhost:3300"
      LOGOUTPAGE_URL: "http://localhost:3300"
      OIDC_PROVIDER_BASE_URL: "https://hslid-dev.t5.fi"
      SECRET_STORE_BASE_PATH: "/mnt/secrets-store"
      SELF_PUBLIC_BASE_URL: "http://localhost:3300"
