#!/usr/bin/env bash
set -eu

psql --username "$POSTGRES_USER" -v ON_ERROR_STOP=1 <<-EOF
    CREATE DATABASE $SESSION_DB;
    \c $SESSION_DB
    CREATE SCHEMA $SESSION_SCHEMA;
    CREATE USER $SESSION_USERNAME PASSWORD '$SESSION_PASSWORD';
    GRANT ALL PRIVILEGES ON SCHEMA $SESSION_SCHEMA TO $SESSION_USERNAME;
EOF
