#!/usr/bin/env bash
set -eu

psql --username "$POSTGRES_USER" -v ON_ERROR_STOP=1 <<-EOF
    CREATE DATABASE auth_session;
    CREATE USER $SPRING_DATASOURCE_USERNAME PASSWORD '$SPRING_DATASOURCE_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE auth_session TO $SPRING_DATASOURCE_USERNAME;
EOF
