#!/usr/bin/env bash
set -eu

psql --username "$POSTGRES_USER" -v ON_ERROR_STOP=1 <<-EOF
    CREATE DATABASE $SESSION_DATASOURCE_DB;
    \c $SESSION_DATASOURCE_DB
    CREATE SCHEMA $SESSION_DATASOURCE_SCHEMA;
    CREATE USER $SESSION_DATASOURCE_USERNAME PASSWORD '$SESSION_DATASOURCE_PASSWORD';
    GRANT ALL PRIVILEGES ON SCHEMA $SESSION_DATASOURCE_SCHEMA TO $SESSION_DATASOURCE_USERNAME;
EOF
