name: CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run_unit_tests:
    name: Run unit tests
    uses: ./.github/workflows/ci.yml

  check_code_formatting:
    name: Check code is formatted with ktlint
    uses: ./.github/workflows/ktlint.yml

  publish_docker_image_to_acr:
    needs:
      - run_unit_tests
      - check_code_formatting
    name: Publish Docker image to ACR
    permissions:
      id-token: write
      contents: read
    uses: HSLdevcom/jore4-tools/.github/workflows/shared-build-and-publish-docker-image.yml@shared-build-and-publish-docker-image-v1
    with:
      docker_image_name: jore4-auth
      build_arm64_image: true
    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  run_e2e_tests:
    needs:
      - run_unit_tests
      - check_code_formatting
      - publish_docker_image_to_acr
    name: Run e2e tests
    runs-on: ubuntu-24.04
    steps:
      - name: Run e2e tests
        uses: HSLdevcom/jore4-tools/github-actions/run-ci@main
        with:
          auth_version: "${{ needs.publish_docker_image_to_acr.outputs.docker_image }}"
