name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: Run auth backend tests
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: mvn clean verify -Pall-tests
