name: Test whether the dockerized version works with docker-compose

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test-docker-compose:
    name: e2e setup locally
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start docker-compose
        run: docker-compose up -d

      - name: Verify that UI is up and running
        run: |
          for i in {1..20}; do
            curl --fail http://localhost:3301 --output /dev/null --silent && break
            sleep 5
            echo $i
          done

      - name: Verify that Auth backend is up and running
        run: |
          for i in {1..20}; do
            curl --fail http://localhost:3301/api/auth/public/v1/login --output /dev/null --silent && break
            sleep 5
            echo $i
          done
