openapi: "3.0.0"
info:
  version: 1.0.0
  title: Kotlin API
  license:
    name: EUPL 2.0
servers:
  - url: https://jore4.hsl.fi/api/auth/public/v1.0
paths:
  /account/active:
    $ref: './account.yaml#/paths/getActiveAccount'
  /login:
    $ref: './authentication.yaml#/paths/login'
  /logout:
    $ref: './authentication.yaml#/paths/logout'
