openapi: "3.0.0"

paths:
  webhook:
    get:
      tags:
        - hasura
      summary: Hasura authorization webhook
      description: >
        Returns the hasura session data of the currently logged in user for the request
        to be authorized or 401 Unauthorized of the request was not authorized.
      operationId: webhook
      produces:
        - application/json
      responses:
        200:
          description: Returns the requested hasura session data.
          content:
            application/json:
              schema:
                $ref: './types/hasura.yaml#/definitions/session'
        401:
          description: The request was not authorized.
